### PR TITLE
Allow the collision detector to detect any blocks

### PR DESCRIPTION
**Pull request by ArtskydJ**

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Hmmm. I think I made a PR against the wrong branch.

Are you only using the gh-pages branch? (If you're not, I do suggest doing so. You can set gh-pages as the default branch and delete master if you want.)

**Comment by spacetag** [comment]
Is there a benefit to having *master* be "bleeding-edge" and *gh-pages* be
"semi-production-worthy"?

Josiah

**Comment by TehShrike** [comment]
I think it's better (at least for a project of this size) to have feature branches that are named for the not-yet-production-ready work being done in them, and then are deleted once they get merged into the main branch, instead of one generic "new code that isn't released yet for some reason" branch.

**Comment by ArtskydJ** [comment]
> Is there a benefit to having *master* be "bleeding-edge" and *gh-pages* be
"semi-production-worthy"?

Right now, I'd say no, because gh-pages isn't close to being a finished product, so you might as well have it be the bleeding edge, in my opinion.

And it removes the need to sync between the master and gh-pages branch.

**Comment by spacetag** [comment]
I merged master into gh-pages, and deleted master.

@ArtskydJ Go ahead and resubmit your pull request against gh-pages -- thanks!

P.S. There's one minor unrelated change in the pull request--FPS_MULTIPLIER got changed to 2--could you put that back to 3 before resubmitting the pull request? Thanks!!! :-)

**Pull request closed without merging**
